name: Clean Blocklist

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Clean blocklist
        run: python scripts/clean_blocklist.py

      - name: Commit cleaned blocklist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --short -- cleaned/blocklist.txt)" ]; then
            git add cleaned/blocklist.txt
            git commit -m "Update cleaned blocklist [skip ci]"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi

      - name: Upload cleaned blocklist artifact
        uses: actions/upload-artifact@v4
        with:
          name: cleaned-blocklist
          path: cleaned/blocklist.txt
